
OLED_ENABLE = no
OLED_DRIVER = SSD1306
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes

VIA_ENABLE = yes
MOUSEKEY_ENABLE = yes
NKRO_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = no

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
